//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TechFix.localhostQuotationApprovalManage {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QuotationApprovalServiceSoap", Namespace="http://tempuri.org/")]
    public partial class QuotationApprovalService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendQuotationForApprovalOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetApprovedQuotationsBySupplierTypeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QuotationApprovalService() {
            this.Url = global::TechFix.Properties.Settings.Default.TechFix_localhostOrderManage1_QuotationApprovalService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendQuotationForApprovalCompletedEventHandler SendQuotationForApprovalCompleted;
        
        /// <remarks/>
        public event GetApprovedQuotationsBySupplierTypeCompletedEventHandler GetApprovedQuotationsBySupplierTypeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendQuotationForApproval", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendQuotationForApproval(int quotationRequestID, string supplierType) {
            object[] results = this.Invoke("SendQuotationForApproval", new object[] {
                        quotationRequestID,
                        supplierType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendQuotationForApprovalAsync(int quotationRequestID, string supplierType) {
            this.SendQuotationForApprovalAsync(quotationRequestID, supplierType, null);
        }
        
        /// <remarks/>
        public void SendQuotationForApprovalAsync(int quotationRequestID, string supplierType, object userState) {
            if ((this.SendQuotationForApprovalOperationCompleted == null)) {
                this.SendQuotationForApprovalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendQuotationForApprovalOperationCompleted);
            }
            this.InvokeAsync("SendQuotationForApproval", new object[] {
                        quotationRequestID,
                        supplierType}, this.SendQuotationForApprovalOperationCompleted, userState);
        }
        
        private void OnSendQuotationForApprovalOperationCompleted(object arg) {
            if ((this.SendQuotationForApprovalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendQuotationForApprovalCompleted(this, new SendQuotationForApprovalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetApprovedQuotationsBySupplierType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetApprovedQuotationsBySupplierType(string supplierType) {
            object[] results = this.Invoke("GetApprovedQuotationsBySupplierType", new object[] {
                        supplierType});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetApprovedQuotationsBySupplierTypeAsync(string supplierType) {
            this.GetApprovedQuotationsBySupplierTypeAsync(supplierType, null);
        }
        
        /// <remarks/>
        public void GetApprovedQuotationsBySupplierTypeAsync(string supplierType, object userState) {
            if ((this.GetApprovedQuotationsBySupplierTypeOperationCompleted == null)) {
                this.GetApprovedQuotationsBySupplierTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApprovedQuotationsBySupplierTypeOperationCompleted);
            }
            this.InvokeAsync("GetApprovedQuotationsBySupplierType", new object[] {
                        supplierType}, this.GetApprovedQuotationsBySupplierTypeOperationCompleted, userState);
        }
        
        private void OnGetApprovedQuotationsBySupplierTypeOperationCompleted(object arg) {
            if ((this.GetApprovedQuotationsBySupplierTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetApprovedQuotationsBySupplierTypeCompleted(this, new GetApprovedQuotationsBySupplierTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SendQuotationForApprovalCompletedEventHandler(object sender, SendQuotationForApprovalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendQuotationForApprovalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendQuotationForApprovalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetApprovedQuotationsBySupplierTypeCompletedEventHandler(object sender, GetApprovedQuotationsBySupplierTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetApprovedQuotationsBySupplierTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetApprovedQuotationsBySupplierTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591